#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &


bspc monitor -d uwu owo ewe rwr iwi æwæ dwd awa fwf nwn
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium 
bspc rule -a mplayer2 state=floating
bspc rule -a catfish state=floating follow=on
bspc rule -a Kupfer.py focus=on
burxvtspc rule -a Screenkey manage=off
#picom --config /home/einarssini/.config/picom/picom.conf & disown
picom & disown
#compiz & disown
nitrogen --restore &
~/.config/polybar/launch.sh
